### ISSUE TITLE
Feature Request: folder scoped docs

### ISSUE THREAD

**Issue by phgn0** [jhm-ciberman/docs_gm#2]
Based on my gamemaker usage I have some improvements in mind:
- generate documentation for all scripts in a (gamemaker) folder on a single page,
with links to subfolders
- ability to set a description / usage text for each folder

I could implement it, but I wanted your opinion :)

btw I really like the work you did here :)

**Comment by jhm-ciberman** [comment]
Hello! 
Let's break it up in parts. 
1 - Do you mean generate a foldername.html file for each folder containing the files for each folder? That sounds like a great idea. I had in mind integrating gm folders in docs_gm but I had no idea how to implement it. I will be busy the next week but I will do it for sure.

2 - that's also a great idea, how do you suggest implementing it? Where does each folder description will be documented? 

Thanks

**Comment by phgn0** [comment]
That's exactly what I meant :)
Regarding 2 we could either have external doc files outside gamemaker, or a special "foldername_doc" script in each folder. This could contain one big comment, maybe with an "@module" tag. 
You already support markdown in comments so it's probably the easiest method.
It would bloat the resource tree a bit though.

**Comment by jhm-ciberman** [comment]
Sorry for the long delay. I am a student so I have a lot of exams in this time of the year. I am now adding unit tests to docs_gm and then I will add this feature. Thanks!

**Comment by jhm-ciberman** [comment]
Hello. Sorry the long delay. I had to refactor ALL the code to make this change. It is partially supported now. You can generate folder scoped documentation (Try the new `module` design inside the `docs_gm-basic` default template by running on the console: `docs_gm generate --design module`)

The second point (folder descriptions) is partially implemented on the codebase, but is not working at the moment. I will add it later. 

Also, now the coverage is 100% and all the classes on the code are totally decoupled, so it should be more easy to mantain the code in the future.

**Comment by jhm-ciberman** [comment]
Now its fully supported. Tell me if you find any issues. (I am sure there are!)
